### ISSUE TITLE
jquery -> jQuery

### ISSUE THREAD

**Issue by fredchu** [MollyLin/mollylin.github.io#1]
`Program language` 區塊的 jquery 如果改成 jQuery 的話會更有專業感，可以考慮更新～

如果 jQuery 改成 JavaScript 或是 ES6 的話就更棒了哈哈，但真的要「會用」再寫唷

**Comment by MollyLin** [comment]
感謝指教 ^^

**Comment by fredchu** [comment]
看到 commit 了！issue 關囉 👍 

https://github.com/MollyLin/mollylin.github.io/commit/16141fc3594c8cd04293276e0d1d46c3f6812a92
